import os

# Mapping alte Basisnamen -> neue Basisnamen
umbenennungen = [
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-1-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand1-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-2-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand2-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-3-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand3-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-4-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand3-2-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-5-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand3-3-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-6-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand3-4-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-7-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand3-5-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-8-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand4-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-9-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand4-2-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-10-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand4-3-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-11-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand4-4-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-12-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand4-5-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-13-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand5-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-14-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand5-2-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-15-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand5-3-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-16-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand5-4-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-17-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand5-5-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-18-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand5-6-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-19-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand6-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-20-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand6-2-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-21-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand6-3-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-22-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand6-4-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-23-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand6-5-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-24-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand7-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-25-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand7-2-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-26-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand7-3-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-27-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand7-4-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-28-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand7-5-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-29-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand8-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-30-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand8-2-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-31-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand8-3-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-32-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand8-4-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-33-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand8-5-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-34-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand8-6-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-35-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand9-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-36-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand9-2-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-37-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand9-3-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-38-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand9-4-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-39-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand9-5-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-40-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand9-6-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-41-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand10-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-42-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand11-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-43-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand12-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-44-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand13-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-45-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand14-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-46-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand15-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-47-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand16-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-48-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand17-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-49-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand18-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-50-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand19-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-51-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand20-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-52-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand21-1-0"),
    ("tts-Video-01_Leitfaehigkeit_und_Widerstand-53-0", "tts-Video-01_Leitfaehigkeit_und_Widerstand22-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-1-0","tts-Video-02_Spannungs_und_Stromquellen1-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-2-0","tts-Video-02_Spannungs_und_Stromquellen2-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-3-0","tts-Video-02_Spannungs_und_Stromquellen3-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-4-0","tts-Video-02_Spannungs_und_Stromquellen4-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-5-0","tts-Video-02_Spannungs_und_Stromquellen5-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-6-0","tts-Video-02_Spannungs_und_Stromquellen6-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-7-0","tts-Video-02_Spannungs_und_Stromquellen7-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-8-0","tts-Video-02_Spannungs_und_Stromquellen7-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-9-0","tts-Video-02_Spannungs_und_Stromquellen7-2-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-10-0","tts-Video-02_Spannungs_und_Stromquellen7-3-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-11-0","tts-Video-02_Spannungs_und_Stromquellen7-4-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-12-0","tts-Video-02_Spannungs_und_Stromquellen8-1-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-13-0","tts-Video-02_Spannungs_und_Stromquellen8-2-0"),
    ("tts-Video-02_Spannungs_und_Stromquellen-14-0","tts-Video-02_Spannungs_und_Stromquellen8-3-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-1-0","tts-Video-03_Kapazitaet_und_Kondensator1-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-2-0","tts-Video-03_Kapazitaet_und_Kondensator2-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-3-0","tts-Video-03_Kapazitaet_und_Kondensator3-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-4-0","tts-Video-03_Kapazitaet_und_Kondensator4-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-5-0","tts-Video-03_Kapazitaet_und_Kondensator4-2-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-6-0","tts-Video-03_Kapazitaet_und_Kondensator5-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-7-0","tts-Video-03_Kapazitaet_und_Kondensator6-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-8-0","tts-Video-03_Kapazitaet_und_Kondensator6-2-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-9-0","tts-Video-03_Kapazitaet_und_Kondensator7-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-10-0","tts-Video-03_Kapazitaet_und_Kondensator8-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-11-0","tts-Video-03_Kapazitaet_und_Kondensator9-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-12-0","tts-Video-03_Kapazitaet_und_Kondensator10-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-13-0","tts-Video-03_Kapazitaet_und_Kondensator11-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-14-0","tts-Video-03_Kapazitaet_und_Kondensator12-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-15-0","tts-Video-03_Kapazitaet_und_Kondensator12-2-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-16-0","tts-Video-03_Kapazitaet_und_Kondensator12-3-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-17-0","tts-Video-03_Kapazitaet_und_Kondensator13-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-18-0","tts-Video-03_Kapazitaet_und_Kondensator13-2-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-19-0","tts-Video-03_Kapazitaet_und_Kondensator13-3-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-20-0","tts-Video-03_Kapazitaet_und_Kondensator13-4-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-21-0","tts-Video-03_Kapazitaet_und_Kondensator13-5-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-22-0","tts-Video-03_Kapazitaet_und_Kondensator14-1-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-23-0","tts-Video-03_Kapazitaet_und_Kondensator14-2-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-24-0","tts-Video-03_Kapazitaet_und_Kondensator14-3-0"),
    ("tts-Video-03_Kapazitaet_und_Kondensator-25-0","tts-Video-03_Kapazitaet_und_Kondensator14-4-0"),
]

ordner=r"/workspace/modul-03-elektrische-bauelemente/TTS"

# Ordner, in dem die Dateien liegen

for alt, neu in umbenennungen:
    for datei in os.listdir(ordner):
        basis, endung = os.path.splitext(datei)
        if basis == alt:
            alter_pfad = os.path.join(ordner, datei)
            neuer_pfad = os.path.join(ordner, neu + endung)
            print(f"{alter_pfad} -> {neuer_pfad}")
            os.rename(alter_pfad, neuer_pfad)
