name: Modul 11

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/getitdigital/texcontainer:main

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: compile Skript
      id: skript
      working-directory: ./modul-11-elektrische-maschinen
      run: latexmk -interaction=nonstopmode -file-line-error -pdf --shell-escape -outdir=TeXAux Skript.tex
    - name: Upload Skript as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Modul-11-Skript
        path: modul-11-elektrische-maschinen/TeXAux/Skript.pdf

    - name: compile Folien
      id: folien
      working-directory: ./modul-11-elektrische-maschinen
      run: latexmk -interaction=nonstopmode -file-line-error -pdf --shell-escape -outdir=TeXAux Folien.tex
    - name: Upload Folien as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Modul-11-Folien
        path: modul-11-elektrische-maschinen/TeXAux/Folien.pdf
