name: Compile Modul 6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/getitdigital/texcontainer:main

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: compile Skript
      id: skript
      working-directory: ./modul-06-magnetische-groessen
      run: latexmk -interaction=nonstopmode -file-line-error -pdf --shell-escape -outdir=TeXAux Skript.tex
    - name: Upload Skript
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: modul-06-magnetische-groessen/TeXAux/Skript.pdf

    - name: compile Folien
      id: folien
      working-directory: ./modul-06-magnetische-groessen
      run: latexmk -interaction=nonstopmode -file-line-error -pdf --shell-escape -outdir=TeXAux Folien.tex
    - name: Upload Folien
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: modul-06-magnetische-groessen/TeXAux/Folien.pdf
